spring:
  application:
    name: habit_tracker

  datasource:
    url: jdbc:postgresql://localhost:5432/habit_tracker_db
    driver-class-name: org.postgresql.Driver
    username: habit_tracker_admin
    password: admin

  liquibase:
    change-log: db/changelog/changelog.xml
    default-schema: habit_tracker_schema
    liquibase-schema: liquibase_schema

springdoc:
  packages-to-scan: org.example.infrastructure.controllers
  paths-to-match: /api/**

jwt:
  token:
    signing-key: c3Nzc3Nzc3NzdWVwci1zaWNyZXQta2V5LWZvci1qd3QtdG9rZW4=